/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securea;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import utils.HashGenerationException;

/**
 *
 * @author Oscar Moreno & Carlos Quimbay
 */
public class NuevoUsuario extends javax.swing.JFrame {

    private Connection conex;
    private Map<String, String> usuarios;
    private static PreparedStatement ps = null;

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario(Connection conex, Map<String, String> user) {
        System.out.println("entró");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        usuarios = user;
        this.conex = conex;
    }

    private NuevoUsuario() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jNombre2 = new javax.swing.JTextField();
        jApellido1 = new javax.swing.JTextField();
        jApellido2 = new javax.swing.JTextField();
        jeMail = new javax.swing.JTextField();
        jUser = new javax.swing.JTextField();
        bAgregar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        jLabel2.setText("Primer Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 79, -1, -1));

        jLabel3.setText("Segundo Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 112, -1, -1));

        jLabel4.setText("Primer Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 150, -1, -1));

        jLabel5.setText("Segundo Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 189, -1, -1));

        jLabel6.setText("e-mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 222, -1, -1));

        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 265, -1, -1));

        jLabel8.setText("Contraseña");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 303, -1, -1));
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 209, -1));
        getContentPane().add(jNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, 209, -1));
        getContentPane().add(jApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 146, 209, -1));
        getContentPane().add(jApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 184, 209, -1));
        getContentPane().add(jeMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 222, 209, -1));
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 209, -1));

        bAgregar.setBackground(new java.awt.Color(51, 153, 255));
        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 354, -1, -1));

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 354, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 298, 209, -1));

        jImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securea/abstract_bg.jpeg"))); // NOI18N
        getContentPane().add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        String pass = "";
        pass = new String(jPasswordField.getPassword());
        String pattern = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
        System.out.println(pass.matches(pattern));
        if (jNombre.getText()
                .equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe indicar el Nombre del usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jApellido1.getText()
                .equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe indicar el Apellido del usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jeMail.getText()
                .equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe indicar el Correo del usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jUser.getText()
                .equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe indicar el Username", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (usuarios.containsKey(jUser.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "El usuario ya existe", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (pass.equals(
                "")) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe indicar el PASSWORD del usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!pass.matches(pattern)) {
            JOptionPane.showMessageDialog(new JFrame(), "La contraseña no cumple con las siguientes restricciones: \n 8 caracteres\n +1 Mayúscula \n +1 Minúscula \n +1 Caracter especial", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!usuarios.containsKey(jUser.getText())) {
            try {
                pass = utils.HashGeneratorUtils.generateSHA256(new String(jPasswordField.getPassword()));
                ps = conex.prepareStatement("insert into SEGURIDAD values (?,?,?,?,?,?,?,?)");
                ps.setString(1, jUser.getText());
                ps.setString(2, pass);
                ps.setString(3, jNombre.getText());
                ps.setString(4, jNombre2.getText());
                ps.setString(5, jApellido1.getText());
                ps.setString(6, jApellido2.getText());
                ps.setString(7, jeMail.getText());
                ps.setString(8, (new Timestamp(System.currentTimeMillis())).toString());
                ps.executeUpdate();
                conex.commit();
                usuarios.put(jUser.getText(), pass);
                JOptionPane.showMessageDialog(new JFrame(), "Usuario credo exitosamente", "Exito", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
                new Principal().setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error al crear usuario", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (HashGenerationException ex) {
                Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Usuario ya esta registrado en el sistema", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCancelar;
    private static javax.swing.JTextField jApellido1;
    private static javax.swing.JTextField jApellido2;
    private javax.swing.JLabel jImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private static javax.swing.JTextField jNombre;
    private static javax.swing.JTextField jNombre2;
    private static javax.swing.JPasswordField jPasswordField;
    private static javax.swing.JTextField jUser;
    private static javax.swing.JTextField jeMail;
    // End of variables declaration//GEN-END:variables
}
