/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securea;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.Otros;

/**
 *
 * @author chArLOz
 */
public class RegFinanciero extends javax.swing.JFrame {

    private static Connection conex;
    private static PreparedStatement ps = null;
    private static ResultSet rs = null;
    private static String username = null;

    /**
     * Creates new form RegMedico
     */
    public RegFinanciero(String username, Connection conex) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.conex = conex;
        this.username = username;
        try {
            ps = conex.prepareStatement("select * from RFINANCIERO where USERN = '" + username + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                activos.setText(rs.getString("ACTIVOS"));
                pasivos.setText(rs.getString("PASIVOS"));
                corriente.setText(rs.getString("CAHORROS"));
                credito.setText(rs.getString("CREDITO"));
            } else {
                Statement st = conex.createStatement();
                int aux= Otros.consecutivofinanciero();
                st.executeUpdate("insert into RFINANCIERO values ("+aux+",0,0,0,0,'" + username + "')");
                conex.commit();
                 activos.setText(rs.getString("0"));
                pasivos.setText(rs.getString("0"));
                corriente.setText(rs.getString("0"));
                credito.setText(rs.getString("0"));
          
            }
        } catch (SQLException ex) {
            Logger.getLogger(PerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form RegFinan
     */
    public RegFinanciero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        activos = new javax.swing.JTextField();
        pasivos = new javax.swing.JTextField();
        corriente = new javax.swing.JTextField();
        credito = new javax.swing.JTextField();
        jImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Registro Financiero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 27, -1, -1));

        jButOK.setText("Salvar");
        jButOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        jLabel2.setText("Activos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Pasivos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Cuenta Corrienta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Tarjeta de Credito");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        getContentPane().add(activos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 101, -1));
        getContentPane().add(pasivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 101, -1));
        getContentPane().add(corriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 101, -1));

        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });
        getContentPane().add(credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 101, -1));

        jImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securea/abstract_bg.jpeg"))); // NOI18N
        getContentPane().add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditoActionPerformed

    private void jButOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOKActionPerformed
        // TODO add your handling code here:
        if (activos.getText().equals("")) {
            try {
                Statement st = conex.createStatement();
               int aux= Otros.consecutivofinanciero();
                st.executeUpdate("insert into RFINANCIERO values ("+aux+",0,0,0,0,'" + username + "')");
                conex.commit();
                JOptionPane.showMessageDialog(new JFrame(), "Registro Financiero creado exitosamente", "Exito", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error al crear Registro Financiero", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            try {
                Statement st = conex.createStatement();
                st.executeUpdate("update RFINANCIERO set ACTIVOS='" + Integer.parseInt(activos.getText())
                        + "',PASIVOS='" + Integer.parseInt(pasivos.getText()) + "',CAHORROS='" + corriente.getText() + "',CREDITO='" + Integer.parseInt(credito.getText()) + "' where USERN='" + username + "'");
                conex.commit();
                JOptionPane.showMessageDialog(new JFrame(), "Registro Financiero modificado exitosamente", "Exito", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error al modificar Registro Financiero", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegFinanciero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activos;
    private javax.swing.JTextField corriente;
    private javax.swing.JTextField credito;
    private javax.swing.JButton jButOK;
    private javax.swing.JLabel jImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pasivos;
    // End of variables declaration//GEN-END:variables
}
