/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securea;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.Otros;

/**
 *
 * @author chArLOz
 */
public class RegMedico extends javax.swing.JFrame {

  private static Connection conex;
    private static PreparedStatement ps = null;
    private static ResultSet rs = null;
    private static String username = null;

    /**
     * Creates new form RegMedico
     */
    public RegMedico(String username, Connection conex) {
        setLocationRelativeTo(null);
        setResizable(false);
        this.conex = conex;
        this.username = username;
        try {
            ps = conex.prepareStatement("select * from RMEDICO where USERN = '" + username + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                estatura.setText(rs.getString("ESTATURA"));
                peso.setText(rs.getString("PESO"));
                rh.setText(rs.getString("RH"));
                alergias.setText(rs.getString("ALERGIAS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private RegMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegMed = new javax.swing.JLabel();
        jButSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rh = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        estatura = new javax.swing.JTextField();
        alergias = new javax.swing.JTextField();
        jImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegMed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelRegMed.setText("Registro Medico");
        getContentPane().add(jLabelRegMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 26, -1, -1));

        jButSalvar.setText("Salvar");
        jButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel1.setText("Estatura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 86, -1, -1));

        jLabel2.setText("Peso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, -1, -1));

        jLabel3.setText("RH");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 179, -1, -1));

        jLabel4.setText("Alergias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 223, -1, -1));

        rh.setEditable(false);
        getContentPane().add(rh, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 174, 110, -1));

        peso.setEditable(false);
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 125, 110, -1));

        estatura.setEditable(false);
        getContentPane().add(estatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 81, 110, -1));

        alergias.setEditable(false);
        getContentPane().add(alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 218, 110, -1));

        jImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securea/abstract_bg.jpeg"))); // NOI18N
        getContentPane().add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 270, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalvarActionPerformed
        // TODO add your handling code here:
        if (peso.getText().equals("")) {
            try {
                Statement st = conex.createStatement();
                st.executeUpdate("insert into RMEDICO values (" + Otros.consecutivoMedico() + "," + Integer.parseInt(peso.getText())
                        + "," + Integer.parseInt(estatura.getText()) + "," + rh.getText() + "," + Integer.parseInt(alergias.getText()) + "," + username + ")");
                
                conex.commit();
                JOptionPane.showMessageDialog(new JFrame(), "Registro Médico creado exitosamente", "Exito", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error al crear Registro médico", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            try {
                Statement st = conex.createStatement();
                st.executeUpdate("update RMEDICO set PESO='" + Integer.parseInt(peso.getText()) + ""
                        + "',ESTATURA='" + Integer.parseInt(estatura.getText()) + "',RH='" + rh.getText() + "',ALERGIAS='" + Integer.parseInt(alergias.getText()) + "' where USERN='" + username + "'");
                conex.commit();
                JOptionPane.showMessageDialog(new JFrame(), "Registro médico modificado exitosamente", "Exito", JOptionPane.PLAIN_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), "Error al modificar Registro médico", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_jButSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergias;
    private javax.swing.JTextField estatura;
    private javax.swing.JButton jButSalvar;
    private javax.swing.JLabel jImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRegMed;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField rh;
    // End of variables declaration//GEN-END:variables
}
